# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - petstore/petstorepetservice/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '70aa685a-f251-437f-aaa2-ef1c1fdfc765'
  imageRepository: 'petstorepetservice'
  containerRegistry: 'azurepetstorecontainerregistry.azurecr.io'
  dockerfilePath: 'petstore/petstorepetservice/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: '$(crImagePullSecretGlobal)'
  
stages:
- stage: Build
  displayName: Build stage
  jobs: 
  - job: Build
    displayName: Build App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo -n -e "{\"version\":\"$(Build.BuildNumber) - $(tag)\"}" > petstore/petstorepetservice/src/main/resources/version.json

    - task: Maven@3
      continueOnError: true 
      displayName: Build Spring Boot Jar
      inputs:
        mavenPomFile: 'petstore/petstorepetservice/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: 'petstore/petstorepetservice/target/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'jaCoCo'
        goals: 'package'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy App
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: texiioazurepetstore-akscluster
              namespace: ingress-petstoreservices
              manifests: |
                $(Pipeline.Workspace)/manifests/petstorepetservice-deployment-everything-enabled.yml
                $(Pipeline.Workspace)/manifests/petstorepetservice-service-everything-enabled.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

          # Add a script to wait for deployment completion
          - script: |
              echo "Waiting for deployment to complete..."
              kubectl rollout status deployment aks-petstorepetservice -n ingress-petstoreservices
            displayName: 'Wait for Deployment'

          # Add any additional steps after the deployment is complete
          - script: |
              echo "Deployment completed. Add your post-deployment steps here."
            displayName: 'Post-Deployment Steps'
